name: 'r-check-version'
description: 'Action to check R that pull request has a new version in DESCRIPTION and NEWS.md'
author: 'jmbarbone'
inputs:
  directory:
    description: 'Package directory'
    required: false
    default: "."
  ignore-dev-version:
    description: 'Ignore dev version in NEWS.md'
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Check version
      id: check
      run: |
        source(
          "${{ github.action_path }}/main.R",
          echo = TRUE,
          max.deparse.length = Inf
        )

      shell: |
        Rscript {0} \
          --directory ${{ inputs.directory }} \
          --ignore-dev-version ${{ inputs.ignore-dev-version }} \
          --repository ${{ github.repository }}
