name: 'r-check-version'
description: 'Action to check R that pull request has a new version in DESCRIPTION and NEWS.md'
author: 'jmbarbone'
inputs:
  ignore-dev-version:
    description: 'Ignore dev version in NEWS.md'
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Check versions
      id: rcheckversion
      run: |
        Rscript r-check-version/main.R \
          --repository ${{ github.repository }} \
          --pull-request-number ${{ github.event.pull_request.number }} \
          --ignore-dev-version ${{ inputs.ignore-dev-version }}
      shell: sh
      working-directory: ${{ inputs.working-directory }}
