name: 'r-check-version'
description: 'Action to check R that pull request has a new version in DESCRIPTION and NEWS.md'
author: 'jmbarbone'
inputs:
  ignore-dev-version:
    description: 'Ignore dev version in NEWS.md'
    required: false
    default: "true"
  directory:
    description: 'Package directory'
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: Check version
      id: check
      run: |
        chmod +x ./r-check-version/main.R
        ./r-check-version/main.R \
          --repository ${{ github.repository }} \
          --pull-request-number ${{ github.event.pull_request.number }} \
          --ignore-dev-version ${{ inputs.ignore-dev-version }}
          --directory ${{ inputs.directory }}
      shell: sh
      working-directory: ${{ github.action_path }}
