name: 'r-check-yaml'
description: 'Action to check that modified yaml/yml files can be read'
author: 'jmbarbone'
inputs:
  directory:
    description: 'Directory to check for yaml/yml files'
    required: false
    default: "."
  pattern:
    description: 'Pattern to match yaml/yml files'
    required: false
    default: ".*\\.(yml|yaml)$"

runs:
  using: "composite"
  steps:
    - name: Check yaml
      id: check
      run: |
        Rscript ${{ github.action_path }}/main.R \
          --directory ${{ inputs.directory }} \
          --pattern ${{ inputs.pattern }}
      shell: sh
