name: 'r-check-yaml'
description: 'Action to check that modified yaml/yml files can be read'
author: 'jmbarbone'
inputs:
  directory:
    description: 'Directory to check for yaml/yml files'
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: Check yaml
      id: check
      run: |
        Rscript ${{ github.action_path }}/main.R \
          --repository ${{ github.repository }} \
          --pull-request-number ${{ github.event.pull_request.number }}
          --directory ${{ inputs.directory }}
      shell: sh
