name: 'r-check-yaml'
description: 'Action to check that modified yaml/yml files can be read'
author: 'jmbarbone'

runs:
  using: "composite"
  steps:
    - name: Check yaml
      id: rcheckyaml
      run: |
        library(gh)
        library(yaml)
        library(fuj)

        cat("::group::Getting files\n")
        get_pull <- gh("GET https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files")

        files <- vapply(get_pull, subset2, NA_character_, "filename")
        files <- files[tolower(tools::file_ext(files)) %in% c("yaml", "yml")]
        cat("::endgroup::\n")

        if (!length(files)) {
          cat("\u2714 No yaml files found\n")
          quit(0)
        }

        cat("::group::Checking yaml files\n")
        check_yaml <- function(x) {
          tryCatch({
            read_yaml(x, error.label = x)
            NA_character_
          }, error = function(e) conditionMessage(e))
        }

        res <- vapply(files, check_yaml, NA_character_, USE.NAMES = FALSE)
        res <- res[!is.na(res)]

        cat("::endgroup::\n")

        if (length(res)) {
          cat(paste("\nu274C", res, collapse = "\n"), "\n")
          quit(1)
        }

        cat("\u274C Success\n")
        quit(0)
      shell: Rscript {0}
      working-directory: ${{ inputs.working-directory }}
