name: 'r-check-yaml'
description: 'Action to check that modified yaml/yml files can be read'
author: 'jmbarbone'

runs:
  using: "composite"
  steps:
    - name: Check yaml
      id: rcheckyaml
      run: |
        Rscript r-check-yaml/main.R \
          --repository ${{ github.repository }} \
          --pull-request-number ${{ github.event.pull_request.number }}
      shell: sh
      working-directory: ${{ inputs.working-directory }}
